buylist/urls.py
from .import views
from django.urls import path

app_name = 'buylist'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('inquiry/', views.InquiryView.as_view(), name='inquiry'),
    path('buylist-list/', views.BuylistListView.as_view(), name='buylist_list'),
    # path('buylist-list/<int:cote>/>', views.BuylistListView.as_view(), name='buylist_list_c'),
    path('buylist-detail/<int:pk>/', views.BuylistDetailView.as_view(), name='buylist_detail'),
    path('buylist-create/', views.BuylistCreateView.as_view(), name='buylist_create'),
    path('buylist-update/<int:pk>/', views.BuylistUpdateView.as_view(), name='buylist_update'),
    path('buylist-delete/<int:pk>/', views.BuylistDeleteView.as_view(), name='buylist_delete'),
    path('redirect/<int:pk>/', views.Swichbyflag.as_view(), name='redirect'),
]

public_buylist/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include

# from . import settings_devs

urlpatterns = [
    path('c&c/', admin.site.urls),
    path('',include('buylist.urls')),
    path('accounts/',include('allauth.urls')),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):

    class Meta:
        verbose_name_plural = 'CustomUser'
# Create your models here.

buylist/models.py
from accounts.models import CustomUser
from django.db import models

# Create your models here.


class buylist (models.Model):

    PRIORITY_CHOICES = (
        ("高", "高"),
        ("中", "中"),
        ("低", "低"),
    )



    
    user = models.ForeignKey(CustomUser,verbose_name='ユーザー',on_delete=models.PROTECT)
    good_name = models.CharField(verbose_name="品名", max_length=50, )
    good_price = models.IntegerField(verbose_name="価格", blank=True, null=True)
    good_quantity = models.IntegerField(verbose_name="個数", blank=True, null=True, default=1)
    good_deadline = models.DateField(verbose_name="購入予定日", auto_now=False, auto_now_add=False)
    good_purohase_data = models.DateField(verbose_name="購入日", auto_now=False, auto_now_add=False, blank=True, null=True)
    good_status = models.BooleanField(blank=True, null=True, default=True)
    good_create_data = models.DateTimeField(verbose_name="作成日時", auto_now_add=True)
    good_purohace_shop = models.CharField(verbose_name='購入店舗', max_length=50, blank=True, null=True)
    good_update_data = models.DateTimeField(verbose_name='更新日時',auto_now=True, auto_now_add=False)
    good_prionty = models.CharField(verbose_name='優先度',max_length=1, choices=PRIORITY_CHOICES,default='低')
    
    
    
    
    
    class Meta:
        verbose_name_plural = 'buylist'

    def __str__(self):
        return self.good_name

buylist/forms.py
from django import forms
from django.core.mail import EmailMessage
from .models import buylist


class InquiryForm(forms.Form):
    name=forms.CharField(label='お名前', max_length=30)
    email=forms.EmailField(label='メールアドレス')
    title=forms.CharField(label='タイトル', max_length=30)
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control col-9'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前を入れてください'
        self.fields['email'].widget.attrs['class'] = 'form-control col-11'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください'
        self.fields['title'].widget.attrs['class'] = 'form-control col-11'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください'
        self.fields['message'].widget.attrs['class'] = 'form-control col-12'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ {}'.format(title)
        message = '送信者名: {0}\nメールアドレス:　{1}/nメッセージ:\n{2}'.format(name, email, message)
        from_email = 'admin@example.com'
        to_list = [
            'test@example.com'
        ]
        cc_list = [
            email
        ]
        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()


class BuylistCreateForm(forms.ModelForm):
    class Meta:
        model = buylist
        fields = ('good_name','good_quantity','good_price','good_deadline','good_purohase_data','good_purohace_shop','good_prionty')
        widgets = {
            'good_prionty': forms.RadioSelect()
        }

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in self.fields.values():
                field.widgets.attrs["class"] = "form-control"

accounts/views.py
from django.shortcuts import render

# Create your views here.

buylist/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib import messages
from datetime import date, datetime
from django.contrib.auth.mixins import LoginRequiredMixin
from .mixins import OnlyYouMixin
import logging
from .models import buylist
from .forms import InquiryForm , BuylistCreateForm

logger= logging.getLogger(__name__)

class IndexView(generic.TemplateView):
    template_name = "index.html"

class InquiryView(generic.TemplateView):
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy('buylist:inquiry')

    def form_valid(self,form):
        form.send_email()
        logger.info('Inquiry sent by {}'.format(form.cleaned_data['name']))
        return super().form_valid(form)



class BuylistListView(LoginRequiredMixin,generic.ListView):
    model = buylist
    template_name =  "buylist_list.html"
    paginate_by = 50

    # def get(self, request, *args, **kwargs):
    #     category_data = self.kwargs['']
    #     memos = Memo.objects.filter(user=self.request.user, good_status=category_data).order_by('good_deadline')
    #     return memos
    def get_queryset(self, **kwargs):
        # category_data = self.kwargs
        # print(category_data)
        buylists = buylist.objects.filter(user=self.request.user).order_by('-good_status', 'good_deadline', 'good_prionty', 'good_name')
        return buylists

class BuylistDetailView(OnlyYouMixin,generic.DetailView):
    model = buylist
    template_name = 'buylist_detail.html'
    # pk_url_kwarg = 'id'

class BuylistCreateView(LoginRequiredMixin,generic.CreateView):
    model = buylist
    template_name = 'buylist_create.html'
    form_class = BuylistCreateForm
    success_url = reverse_lazy('buylist:buylist_list')

    def form_valid(self, form):
        buylist = form.save(commit=False)
        buylist.user = self.request.user
        buylist.save()
        messages.success(self.request,"欲しいものを追加しました。")
        return super().form_valid(form)
        
    def form_invalid(self, form):
        messages.error(self.request,"欲しいものの追加に失敗しました")

class BuylistUpdateView(OnlyYouMixin,generic.UpdateView):
    model = buylist
    template_name = 'buylist_update.html'
    form_class = BuylistCreateForm

    def get_success_url(self):
        return reverse_lazy('buylist:buylist_detail',kwargs={'pk':self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request,'欲しいものを更新しました')
        return super().form_valid(form)

    def form_vallid(self, form):
        messages.success(self.request,'欲しいものの更新を失敗しました')
        return super().form_valid(form)

class BuylistDeleteView(OnlyYouMixin, generic.DeleteView):
    model =  buylist
    template_name = 'buylist_delete.html'
    success_url = reverse_lazy('buylist:buylist_list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request,"欲しいものを削除しました。")
        return super().delete(request,*args,**kwargs)

class Swichbyflag(generic.RedirectView):
    url = reverse_lazy('buylist:buylist_list')
#    messages.success(self.request,'リダイレクト成功')
    
    def get(self, request, *args, **kwargs):
        url = self.get_redirect_url(*args, **kwargs)
        
        id = kwargs['pk']
        s = buylist.objects.filter(pk=id).first()
        if s.good_status == 1 :
            s.good_status = 0
            s.good_purohase_data = date.today()
        elif s.good_status == 0 :
            s.good_status = 1
            s.good_purohase_data = None
        
        s.save()
        return redirect(url)

myview = BuylistListView.as_view()

buylist/templates/base.html
{% load static %}

<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title%}{% endblock %}</title>
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'icon/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'icon/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'icon/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'icon/applicon/e-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'icon/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'icon/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'icon/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'icon/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'icon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192" href="{% static 'icon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'icon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'icon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'icon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'icon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'icon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900,">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,700,700i,900,900i,">
    <!--    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">-->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/one-page-wonder.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/clean-blog.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <script src="{% static 'fontawesome_free/js/all.min.js' %}"></script>
    <link href="{% static 'fontawesome_free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesome_free/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesome_free/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesome_free/css/solid.css' %}" rel="stylesheet" type="text/css">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    {% block head %}{% endblock %}
</head>
<body>
<div id="wrapper">
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
        <div class="container">
            {% if user.is_authenticated %}

            <a href="{% url 'buylist:buylist_list' %}" class="navbar-brand font-type">Wish list</a>

            {% else %}
            <a href="{% url 'buylist:index' %}" class="navbar-brand font-type">Wish list</a>

            {% endif %}

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">

                    {% if user.is_authenticated %}

                    <li class="nav-item">
                        <a href="{% url 'account_logout' %}" class="nav-link font-type"><i
                                class="fas fa-address-card"></i>ログアウト</a>
                    </li>

                    {% else %}

                    <li class="nav-item {% block active_signup %}{% endblock %}">
                        <a href="{% url 'account_signup' %}" class="nav-link font-type">ユーザー登録</a>
                    </li>
                    <li class="nav-item {% block active_login %}{% endblock %}">
                        <a href="{% url 'account_login' %}" class="nav-link font-type">ログイン</a>
                    </li>

                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block header%}{% endblock %}

    {% if messages %}
    <div class="container">
        <div class="row">
            <div class="my-div-style w-100">
                <ul class="messages" style="list-style:none;">
                    {% for message in messages %}
                    <li {%if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    {% endif %}

    {% block contents%}{% endblock %}
    <footer class="py-3 bg-black">
        <div class="container">
            <p class="m-0 text-center text-white small font-title">Copyright &copy; Koutaro Project 2021</p>
        </div>
    </footer>
</div>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

{% comment %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
{% endcomment %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"
        integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em"
        crossorigin="anonymous"></script>

</body>
</html>

buylist/templates/buylist_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}作成|Wish_List{% endblock %}

{% block active_buylist_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="col-lg col-md-10 mx-auto">
            <div class="clearfix">
                <div class="my-div-style w-100">
                    <div class="h2 mb-5">
                        欲しいもの <small>新規作成</small>
                    </div>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <table class="table">
                            {{ form.as_table }}
                        </table>
                        <button class="btn btn-primary" type="submit">作成</button>
                        <a href="{% url 'buylist:buylist_list' %}" class="btn btn-secondary">戻る</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
      $(function () {
          // 日付は、年-月-日 の形式でお願いする。
          let dateFormat = 'yy-mm-dd';
          $('#id_good_deadline').datepicker({
              dateFormat: dateFormat
          });
          $('#id_good_purchase_data').datepicker({
              dateFormat: dateFormat
          });
      });


</script>
{% endblock %}

buylist/templates/buylist_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}削除|Buylist{% endblock %}
{% block active_buylist %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <div class="col-lg col-md-10 mx-auto">
                <div class="h2 mb-5">
                    欲しいもの <small>削除</small>
                </div>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <p>ほんとに削除しますか？</p>
                    <button class="btn btn-primary mt-5" type="submit">削除</button>
                    <a href="{% url 'buylist:buylist_detail' object.pk %}" class="btn btn-secondary mt-5">キャンセル</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

buylist/templates/buylist_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}詳細|Wish_List{% endblock %}
{% block active_buylist_list %}active{% endblock %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/clean-blog.min.css' %}">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="my-div-style w-100">
        <div class="h2 mb-5">
            欲しいもの <small>詳細</small>
        </div>
        <div class="row">
            <div class="col-5">
                <strong>ほしいもの</strong>
            </div>
            <div class="col-9">
                {{object.good_name|default_if_none:""}}
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-5">
                <strong>個数</strong>
            </div>
            <div class="col-9">
                {{ object.good_quantity|default_if_none:"" }}個
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-5">
                <strong>価格</strong>
            </div>
            <div class="col-9">
                {{ object.good_price|default_if_none:"0" }}円
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-5">
                <strong>購入予定日</strong>
            </div>
            <div class="col-9">
                {{object.good_deadline}}
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-5">
                <strong>優先度</strong>
            </div>
            <div class="col-9">
                {{object.good_prionty}}
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-5">
                <strong>購入日</strong>
            </div>
            <div class="col-9">
                {{object.good_purohase_data|default_if_none:""}}
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-5">
                <strong>制作日時</strong>
            </div>
            <div class="col-9">
                {{object.good_create_data}}
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-5">
                <strong>更新日時</strong>
            </div>
            <div class="col-9">
                {{object.good_update_data}}
            </div>
        </div>

        <a href="{% url 'buylist:buylist_update' buylist.pk %}" class="btn btn-success mt-5 mb-3 icon"><i class="fas fa-edit"></i>編集</a>
        <a href="{% url 'buylist:buylist_delete' buylist.pk %}" class="btn btn-primary mt-5 mb-3 icon"><i class="fas fa-trash-alt"></i>削除</a>
        <a href="{% url 'buylist:buylist_list' %}" class="btn btn-secondary mt-5 mb-3 icon"><i class="fas fa-undo"></i>戻る</a>
    </div>
    
</div>
{% endblock %}

buylist/templates/buylist_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}一覧|Wish_List{% endblock %}

{% block active_buylist_list %}active{% endblock %}


{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <div class="col-lg col-md-10 mx-auto">
                <div class="clearfix">
<!--                    <a href="{% url 'buylist:buylist_list'  %}">test</a>-->
                    <div class = "h2 mb-5">
                        欲しいもの <small>一覧</small>
                        <a href="{% url 'buylist:buylist_create' %}">
                            <i class="fas fa-plus-circle float-right"></i>
<!--                            <i class="far fa-2x fa-plus-square float-right mb-5"></i>-->
                        </a>
                    </div>

                </div>
                {% for buylist in buylist_list %}
                    {% if buylist.good_status == 1 %}
                    <div class="post-preview">
                        <a href="{% url 'buylist:buylist_detail' buylist.pk %}" >
                            <div class="h2 post-title">
                                {{buylist.good_name}}　
                                <a href="{% url 'buylist:redirect' buylist.pk %}" class="btn btn-danger text-white float-right "><i class="fas fa-2x fa-shopping-cart"></i></a>
                            </div>
                        </a>
                        {% if buylist.good_price == None %}
                        <div class="post-meta col-md-5">優先度：{{buylist.good_prionty}}</div>
                        {% else %}
                        <div class="post-meta col-md-5">価格：{{buylist.good_price}}円</div>
                        {% endif %}
                        <div class="post-meta col-md-6 col-10">購入締切：{{buylist.good_deadline}}</div>
                        <div class="post-meta col-md-7">購入個数：{{buylist.good_quantity}}個</div>
                   </div>

                    <hr>
                   {% elif buylist.good_status == 0 %}
                   <div class="post-preview">
                      <a href="{% url 'buylist:buylist_detail' buylist.pk %}"　class="false">
                          <div class="h2 post-title">
                              {{buylist.good_name}}
                              <a href="{% url 'buylist:redirect' buylist.pk %}" class="btn btn-primary text-white float-right">
                                  <i class="fas fa-2x fa-times-circle"></i>
<!--                                  <i class="fas fa-2x fa-undo-alt"></i>-->
                              </a>
                          </div>
                      </a>

                      <div class="post-meta col-md-6 col-10">購入日：{{buylist.good_purohase_data}}</div>
                      <div class="post-meta col-5">{{buylist.good_purchase_shop|default_if_none:"" }}</div>

                    </div>


                    <hr>
                    {% endif %}
                    {% empty %}
                        <p>欲しいものがありません。</p>
                    {% endfor %}
                {% include 'pagination.html'%}
            </div>
        </div>
    </div>
</div>
{% endblock %}

buylist/templates/buylist_update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}編集|Wish_List{% endblock %}
{% block active_buylist_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <div class="col-lg col-md-10 mx-auto">
                <div class="h2 mb-5">
                    欲しいもの <small>編集</small>
                </div>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <table class="table">
                        {{ form.as_table }}
                    </table>
                    <button class="btn btn-primary" type="submit">更新</button>
                    <a href="{% url 'buylist:buylist_detail' buylist.pk %}" class="btn btn-secondary ml-2">キャンセル</a>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

{% endblock %}

buylist/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Wish List{%endblock %}

{% block header %}
  <header class="masthead text-center text-white">
    <div class="masthead-content">
      <div class="container">
        <h1 class="masthead-heading mb-0 font-title">Wish List</h1>
        <h2 class="masthead-subheading mb-0 font-type">あなた専用の欲しいものリスト</h2>
        <a href="{% url 'account_login' %}" class="btn btn-primary btn-xl rounded-pill mt-5 font-type">ログイン</a>
      </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
  </header>
{% endblock %}

{% block contents %}
  <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6 order-lg-2">
          <div class="p-4">
            <img class="img-fluid rounded-circle" src="{% static 'img/01.png'%}" alt="">
          </div>
        </div>
        <div class="col-lg-6 order-lg-1">
          <div class="p-4">
            <div class="display-4 font-title">Wish List</div>
            <p class="font-type">web上で欲しいものリストの管理が<br>
              出来るだけじゃなく、<br>
              作成・編集・削除ができるのです!</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6">
          <div class="p-4">
            <img class="img-fluid rounded-circle" src="{% static 'img/02.png' %}" alt="">
          </div>
        </div>
        <div class="col-lg-6">
          <div class="p-4">
            <div class="display-4 font-title">Save Wish List</div>
            <p class="font-type">あなたの欲しいものリストが<br />
               ななっ、なんと！<br />
              Web上に保存することができます！</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-6 order-lg-2">
          <div class="p-4">
            <img class="img-fluid rounded-circle" src="{% static 'img/03.png'%}" alt="">
          </div>
        </div>
        <div class="col-lg-6 order-lg-1">
          <div class="p-4">
            <div class="display-4 font-title">Membership</div>
            <p class="font-type">会員制のWeb欲しいもの<br />リスト管理サービス</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  {% endblock %}

buylist/templates/inquiry.html
{% extends 'base.html' %}

{% block title %}お問い合わせ|Wish_List{% endblock %}
{% block active_inquiry %}active{% endblock %}
{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <form method="post">
                {% csrf_token %}

                {{ form.non_errors }}

                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">
                            <strong>{{fields.label_tag}}</strong>
                        </label>
                        <div class="col-sm-8">
                            {{field}}
                            {{field.errors}}
                        </div>
                    </div>
                {% endfor %}

                <div class="offset-sm-4 col-sm-8">
                    <button class="btn btn-primary" type="submit">送信</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

buylist/templates/pagination.html
<nav aria-label="Page navigation example">

    <ul class="pagination justify-content-center pagination-lg g-mt-28 g-mb-28">
        <!-- 前へ の部分 -->
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        <!-- 数字の部分 -->
        {% for num in page_obj.paginator.page_range %}
            {% if num <= page_obj.number|add:5 and num >= page_obj.number|add:-5 %}

                {% if page_obj.number == num %}
                    <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endif %}
        {% endfor %}

        <!-- 次へ の部分 -->
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>

</nav>